### ISSUE TITLE
Implement versioning of the project (tagging)

### ISSUE THREAD

**Issue by DominicWatson** [jcberquist/aws-cfml#6]
Hi there,  we're using your library in this project: https://github.com/pixl8/s3-commandbox-commands - many thanks for the hard work! :)

We're pulling in your project as a commandbox dependency and simply pointing to your github repo. The issue with this is that, when you change the code, our project can then break (as it did with the recent rename of the 'region' argument to the API).

Simple tagging with git would be enough for us to be able to peg the dependency to a specific version - but you could consider registering the project with forgebox also and releasing versions there also.

Anyways, its not a huge deal - but would be helpful for others I think. Happy to help getting setup to push to forgebox if wanted too.

Regards,

Dominic

**Comment by jcberquist** [comment]
@DominicWatson: I did know about your project and I am interested in using it :) I am sorry about breaking it - I was afraid of that, which is why I opened the pull request there.

I am actually in the process of trying to update some of my libraries so that I can get them on forgebox and then pull them into our projects from there. I will need to figure things out - though I have used forgebox, I have yet to put anything up there. So any guidance you could provide would be appreciated. Thanks!

Also, would it be possible to update your commandbox command so that it could be used without supplying credentials? Then my aws library should (hopefully!) try to obtain credentials from a server's IAM role - which would be useful to me.

**Comment by DominicWatson** [comment]
Ah, doh - somehow I completely missed that PR. Have had my head buried in all sorts of things. Thanks for the PR :)

Re pushing to forgebox, we happen to be using https://travis-ci.org for our open source stuff. You can see the `.travis.yml` file and `publish.sh` file that does the automation in the *s3-commandbox-commands* project  - travis super easy as you just link it to your github account. you might have to play with the right category for forgebox in terms of setting up your box.json though.

> ... try to obtain credentials from a server's IAM role...

Sounds neat! It would be good to try it out first if you have a working environemnt with box and a configured IAM role on the server... You'd need to edit `~/.CommandBox/cfml/modules/s3-commandbox-commands/endpoints/s3.cfc` to be able to directly play with it in a working environment...

**Comment by jcberquist** [comment]
@DominicWatson, it took some experimentation, but I think I have added this to forgebox successfully: [aws-cfml](https://www.forgebox.io//view/aws-cfml). Can you verify that what I have done will work for you?
